// @ts-check
/*

    Inner Core Docs: Inner Core, Core Engine and Horizon documentation
    Copyright (C) 2022  Nernar (https://github.com/nernar)

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

	Maintained and distributed by MaXFeeD (maxfeed.nernar@outlook.com)

*/

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
	tutorialSidebar: [
		{
			type: 'doc',
			id: 'intro'
		},
		{
			type: 'category',
			label: 'Getting Started',
			link: {
				type: 'generated-index'
			},
			collapsed: false,
			items: [
				{
					type: 'autogenerated',
					dirName: 'getting-started'
				}
			]
		},
		{
			type: 'category',
			label: 'Basics',
			link: {
				type: 'generated-index'
			},
			items: [
				{
					type: 'autogenerated',
					dirName: 'basics'
				}
			]
		},
		{
			type: 'category',
			label: 'Events',
			link: {
				type: 'generated-index'
			},
			items: [
				{
					type: 'autogenerated',
					dirName: 'events'
				}
			]
		},
		{
			type: 'category',
			label: 'Items',
			link: {
				type: 'generated-index'
			},
			items: [
				{
					type: 'autogenerated',
					dirName: 'items'
				}
			]
		},
		{
			type: 'category',
			label: 'Blocks',
			link: {
				type: 'generated-index'
			},
			items: [
				{
					type: 'autogenerated',
					dirName: 'blocks'
				}
			]
		},
		{
			type: 'category',
			label: 'Environment',
			link: {
				type: 'generated-index'
			},
			items: [
				{
					type: 'autogenerated',
					dirName: 'environment'
				}
			]
		},
		{
			type: 'category',
			label: 'Generation',
			link: {
				type: 'generated-index'
			},
			items: [
				{
					type: 'autogenerated',
					dirName: 'generation'
				}
			]
		},
		{
			type: 'category',
			label: 'Saves',
			link: {
				type: 'generated-index'
			},
			items: [
				{
					type: 'autogenerated',
					dirName: 'saves'
				}
			]
		},
		{
			type: 'category',
			label: 'Player',
			link: {
				type: 'generated-index'
			},
			items: [
				{
					type: 'autogenerated',
					dirName: 'player'
				}
			]
		},
		{
			type: 'category',
			label: 'UIs',
			link: {
				type: 'generated-index'
			},
			items: [
				{
					type: 'autogenerated',
					dirName: 'ui'
				}
			]
		},
		{
			type: 'category',
			label: 'Entities',
			link: {
				type: 'generated-index'
			},
			items: [
				{
					type: 'autogenerated',
					dirName: 'entities'
				}
			]
		},
		{
			type: 'category',
			label: 'Tile Entities',
			link: {
				type: 'generated-index'
			},
			items: [
				{
					type: 'autogenerated',
					dirName: 'block-entities'
				}
			]
		},
		{
			type: 'category',
			label: 'Renders',
			link: {
				type: 'generated-index'
			},
			items: [
				{
					type: 'autogenerated',
					dirName: 'renders'
				}
			]
		},
		{
			type: 'category',
			label: 'Dimensions',
			link: {
				type: 'generated-index'
			},
			items: [
				{
					type: 'autogenerated',
					dirName: 'dimensions'
				}
			]
		},
		{
			type: 'category',
			label: 'Structures',
			link: {
				type: 'generated-index'
			},
			items: [
				{
					type: 'autogenerated',
					dirName: 'structures'
				}
			]
		},
		{
			type: 'category',
			label: 'Publishing',
			link: {
				type: 'generated-index'
			},
			items: [
				{
					type: 'autogenerated',
					dirName: 'publishing'
				}
			]
		},
		{
			type: 'doc',
			id: 'future-steps'
		}
	]
};
