name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    env:
      publish-directory: ./docs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: google/wireit@setup-github-actions-caching/v1

      - name: Install dependencies
        run: npm ci
      - name: Build documentation
        run: npm run typedoc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy
          publish_dir: ${{ env.publish-directory }}
          full_commit_message: ${{ github.event.head_commit.message }}
