// @ts-check
/*

    Inner Core API: Core Engine API Reference
    Copyright (C) 2022  Nernar (https://github.com/nernar)

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

	Maintained and distributed by MaXFeeD (maxfeed.nernar@outlook.com)

*/

const path = require('path');
const fs = require('fs');

const dirents = fs.readdirSync(path.join(__dirname, 'www'), {
	withFileTypes: true
});
const folders = [];
const files = [];

for (const dirent of dirents) {
	if (dirent.isFile() && (dirent.name == 'index.md' || dirent.name == 'readme.md')) {
		continue;
	}
	if (dirent.isFile() || dirent.isDirectory()) {
		(dirent.isDirectory() ? folders : files).push(dirent.name);
	}
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
	referenceSidebar: folders.map(function(value) {
		return {
			type: 'category',
			link: {
				type: 'doc',
				id: value + '/index'
			},
			items: [
				{
					type: 'autogenerated',
					dirName: value
				}
			],
			label: value
		};
	}).concat(
		// @ts-ignore
		files.map(function(value) {
			return {
				type: 'doc',
				id: value.replace(/\.mdx?$/i, '')
			};
		}
	))
};
